version: '3.8'

services:
  finance-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - PORT=8000
    restart: unless-stopped 