# Google Sheets configuration
# Maps human-friendly names to Google Sheets IDs and default worksheets

finance_2025:
  id: "PLACEHOLDER_ID"
  sheet: Main

budget_2025:
  id: "PLACEHOLDER_ID"
  sheet: Main

balance_sheet:
  id: PLACEHOLDER_ID
  sheet: Main

income_statement:
  id: PLACEHOLDER_ID
  sheet: Main 
